# Generated by Django 4.2.7 on 2023-11-30 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotionapp', '0003_imagemodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImageModel',
            new_name='DesignModel',
        ),
    ]
